// =====================================================================
// Vocabulário do módulo Flashcards — importado do protótipo Google Apps
// Script "Francês na Mira" (SeedData.gs + SeedData_VidaCotidiana.gs):
// conectores/expressões de argumentação (DELF/DALF/TEF/TCF), vocabulário
// de vida cotidiana (família, moradia, cidade, meio ambiente, tecnologia,
// saúde, sociedade, psicologia, cultura, economia), verbos essenciais e
// números por extenso. Consumido só por backend/seed/seedFlashcards.js —
// não é servido diretamente pro front-end.
// =====================================================================

const VOCAB_SEED = [
  // ---- VERBOS ----
  {fr:"il s'agit de", pt:"trata-se de", classe:"Verbo/Locução", categoria:"Introduzir um tema", frase:"Aujourd'hui, il s'agit d'un sujet très polémique."},
  {fr:"susciter", pt:"suscitar, provocar", classe:"Verbo", categoria:"Debate", frase:"Ce sujet suscite encore beaucoup de débats."},
  {fr:"aborder", pt:"abordar", classe:"Verbo", categoria:"Introduzir um tema", frase:"Je vais aborder un sujet urgent."},
  {fr:"évoquer", pt:"evocar, mencionar", classe:"Verbo", categoria:"Introduzir um tema", frase:"Il a évoqué plusieurs solutions possibles."},
  {fr:"mentionner", pt:"mencionar", classe:"Verbo", categoria:"Introduzir um tema", frase:"Elle a mentionné ce problème dans son discours."},
  {fr:"saisir", pt:"compreender / segurar / aproveitar", classe:"Verbo", categoria:"Compreensão", frase:"Il faut saisir l'ampleur du problème."},
  {fr:"mener à", pt:"levar a", classe:"Verbo", categoria:"Causa e consequência", frase:"Cela peut mener à des conséquences graves."},
  {fr:"aboutir", pt:"culminar em, resultar em", classe:"Verbo", categoria:"Causa e consequência", frase:"Les négociations ont abouti à un accord."},
  {fr:"cela représente", pt:"isso representa", classe:"Verbo/Locução", categoria:"Descrever dados", frase:"Cela représente une part importante de la population."},
  {fr:"constituer", pt:"constituir", classe:"Verbo", categoria:"Descrever dados", frase:"Cela constitue un enjeu majeur pour la société."},
  {fr:"consister à", pt:"consistir em", classe:"Verbo", categoria:"Definição", frase:"La solution consiste à sensibiliser le public."},
  {fr:"primer", pt:"prevalecer, ter prioridade", classe:"Verbo", categoria:"Argumentação", frase:"L'intérêt collectif doit primer sur l'intérêt individuel."},
  {fr:"éviter", pt:"evitar", classe:"Verbo", categoria:"Argumentação", frase:"Il faut éviter de généraliser."},
  {fr:"jouir de", pt:"gozar de, usufruir", classe:"Verbo", categoria:"Direitos", frase:"Chaque citoyen doit jouir des mêmes droits."},
  {fr:"prendre conscience de", pt:"conscientizar-se de", classe:"Verbo/Locução", categoria:"Argumentação", frase:"Il est essentiel de prendre conscience de ce problème."},
  {fr:"mettre en place", pt:"implementar, estabelecer", classe:"Verbo/Locução", categoria:"Solução", frase:"Le gouvernement doit mettre en place de nouvelles mesures."},
  {fr:"mettre en évidence", pt:"evidenciar, destacar", classe:"Verbo/Locução", categoria:"Argumentação", frase:"Cette étude met en évidence un problème sérieux."},
  {fr:"mettre en avant", pt:"colocar em destaque, ressaltar", classe:"Verbo/Locução", categoria:"Argumentação", frase:"Il met en avant les avantages de cette solution."},
  {fr:"subir", pt:"sofrer, ser vítima de", classe:"Verbo", categoria:"Consequência", frase:"Les jeunes subissent une forte pression sociale."},
  {fr:"issu(e) de", pt:"originário de, proveniente de", classe:"Verbo/Adjetivo", categoria:"Origem", frase:"Ce problème est issu d'un manque d'éducation."},
  {fr:"parvenir à", pt:"conseguir, chegar a", classe:"Verbo", categoria:"Resultado", frase:"Ils sont parvenus à un consensus."},
  {fr:"croître", pt:"crescer, aumentar", classe:"Verbo", categoria:"Dados/Evolução", frase:"Le chômage croît de manière alarmante."},
  {fr:"prôner", pt:"defender, pregar, advogar por", classe:"Verbo", categoria:"Opinião", frase:"Certains prônent une réforme radicale."},
  {fr:"remettre en question / en cause", pt:"questionar, colocar em xeque", classe:"Verbo/Locução", categoria:"Argumentação", frase:"Il faut remettre en question ce système."},
  {fr:"axer / ancrer", pt:"centrar / ancorar (em um eixo)", classe:"Verbo", categoria:"Argumentação", frase:"Son discours est axé sur l'écologie."},
  {fr:"percevoir / perçu(e)(s)", pt:"perceber / percebido(a/s)", classe:"Verbo/Particípio", categoria:"Percepção", frase:"Ce phénomène est perçu comme une menace."},
  {fr:"biaiser / le biais", pt:"distorcer / o viés", classe:"Verbo/Substantivo", categoria:"Argumentação", frase:"Les médias biaisent parfois l'information."},
  {fr:"pousser à", pt:"levar a, impulsionar a", classe:"Verbo", categoria:"Causa e consequência", frase:"La pression sociale pousse à la surconsommation."},
  {fr:"(dé)pourvoir / fournir / garnir / garantir", pt:"prover / fornecer / equipar / garantir", classe:"Verbo", categoria:"Solução", frase:"L'État doit fournir des ressources suffisantes."},
  {fr:"livrer / livraison", pt:"entregar / entrega", classe:"Verbo/Substantivo", categoria:"Cotidiano", frase:"Le colis a été livré à temps."},
  {fr:"songer / envisager", pt:"pensar em, cogitar / considerar, planejar", classe:"Verbo", categoria:"Opinião", frase:"Il faut envisager plusieurs solutions."},
  {fr:"toucher", pt:"afetar, atingir", classe:"Verbo", categoria:"Consequência", frase:"Ce phénomène touche toutes les tranches d'âge."},
  {fr:"répandre / répandu(e)", pt:"espalhar / difundido, comum", classe:"Verbo/Adjetivo", categoria:"Frequência", frase:"C'est une pratique très répandue aujourd'hui."},
  {fr:"constater", pt:"constatar", classe:"Verbo", categoria:"Observação", frase:"On peut constater une nette évolution."},
  {fr:"surpasser / surmonter", pt:"superar / ultrapassar (dificuldade)", classe:"Verbo", categoria:"Solução", frase:"Il faut surmonter ces obstacles ensemble."},
  {fr:"figurer", pt:"figurar, constar", classe:"Verbo", categoria:"Dados", frase:"Ce pays figure parmi les plus touchés."},
  {fr:"procéder", pt:"proceder, agir de determinada forma", classe:"Verbo", categoria:"Argumentação", frase:"Il convient de procéder par étapes."},
  {fr:"comporter", pt:"comportar, incluir", classe:"Verbo", categoria:"Descrição", frase:"Cette mesure comporte plusieurs risques."},
  {fr:"anéantir / saper", pt:"aniquilar / minar, solapar", classe:"Verbo", categoria:"Consequência", frase:"Cela risque de saper la confiance du public."},
  {fr:"franchir", pt:"romper, ultrapassar (um limite)", classe:"Verbo", categoria:"Consequência", frase:"On a franchi un cap inquiétant."},

  // ---- LOCUÇÕES / CONECTORES LÓGICOS ----
  {fr:"portant sur / qui porte sur", pt:"que trata sobre", classe:"Locução", categoria:"Introduzir um tema", frase:"Un sujet portant sur l'environnement."},
  {fr:"pour faire face à cette contrainte/cet enjeu", pt:"para enfrentar essa dificuldade/esse desafio", classe:"Locução", categoria:"Solução", frase:"Pour faire face à ce défi, il faut agir vite."},
  {fr:"face à cette réalité", pt:"diante dessa realidade", classe:"Locução", categoria:"Introdução de argumento", frase:"Face à cette réalité, des mesures s'imposent."},
  {fr:"vu que / étant donné que", pt:"visto que / dado que", classe:"Locução", categoria:"Causa", frase:"Étant donné que le problème persiste, il faut réagir."},
  {fr:"de surcroît / en outre / de plus", pt:"além disso, ademais", classe:"Locução", categoria:"Adição", frase:"De surcroît, cette mesure coûte cher."},
  {fr:"au-delà de", pt:"além de", classe:"Locução", categoria:"Adição", frase:"Au-delà de l'aspect économique, il y a un enjeu social."},
  {fr:"en effet / car", pt:"com efeito / pois", classe:"Locução", categoria:"Explicação", frase:"En effet, les chiffres le confirment."},
  {fr:"c'est-à-dire", pt:"ou seja, isto é", classe:"Locução", categoria:"Explicação", frase:"C'est-à-dire que rien n'est encore décidé."},
  {fr:"par rapport à", pt:"em relação a", classe:"Locução", categoria:"Comparação", frase:"Par rapport à l'année dernière, la situation a empiré."},
  {fr:"à l'égard de / à cet égard", pt:"em relação a / a esse respeito", classe:"Locução", categoria:"Comparação", frase:"À cet égard, plusieurs mesures ont été proposées."},
  {fr:"en ce qui concerne / concernant", pt:"no que diz respeito a", classe:"Locução", categoria:"Introdução de tópico", frase:"En ce qui concerne l'éducation, beaucoup reste à faire."},
  {fr:"voire (et même)", pt:"ou até mesmo", classe:"Locução", categoria:"Ênfase", frase:"C'est difficile, voire impossible."},
  {fr:"quoi que / quoique", pt:"seja o que for que / embora", classe:"Locução", categoria:"Concessão", frase:"Quoiqu'il en soit, il faut agir."},
  {fr:"lors de / lorsque", pt:"durante / quando", classe:"Locução", categoria:"Tempo", frase:"Lors de la réunion, le sujet a été abordé."},
  {fr:"or", pt:"ora, no entanto (oposição)", classe:"Conjunção", categoria:"Oposição", frase:"Or, les faits montrent le contraire."},
  {fr:"permettant ainsi", pt:"permitindo assim", classe:"Locução", categoria:"Consequência", frase:"...permettant ainsi une meilleure inclusion."},
  {fr:"ainsi que", pt:"bem como, assim como", classe:"Locução", categoria:"Adição", frase:"Les jeunes ainsi que les adultes sont concernés."},
  {fr:"à l'instar de", pt:"a exemplo de, como", classe:"Locução", categoria:"Comparação", frase:"À l'instar de la France, d'autres pays agissent."},
  {fr:"en guise de", pt:"a título de, como", classe:"Locução", categoria:"Introdução", frase:"En guise de conclusion, je dirais que..."},
  {fr:"et ce, en partie / en raison de", pt:"e isso, em parte / por causa de", classe:"Locução", categoria:"Causa", frase:"Et ce, en raison d'un manque de moyens."},
  {fr:"plutôt que", pt:"em vez de", classe:"Locução", categoria:"Comparação", frase:"Plutôt que d'ignorer le problème, il faut l'affronter."},
  {fr:"pourvu que / à condition que", pt:"desde que, contanto que", classe:"Locução", categoria:"Condição", frase:"Ça peut marcher, pourvu qu'on s'y engage."},
  {fr:"il convient de", pt:"convém, é apropriado", classe:"Locução impessoal", categoria:"Argumentação", frase:"Il convient de rappeler les faits avant d'agir."},
  {fr:"à défaut", pt:"na falta de, senão", classe:"Locução", categoria:"Condição", frase:"À défaut d'accord, aucune mesure ne sera prise."},
  {fr:"dû à", pt:"devido a", classe:"Locução", categoria:"Causa", frase:"C'est dû à un manque de communication."},

  // ---- ADVÉRBIOS ----
  {fr:"apparemment", pt:"aparentemente", classe:"Advérbio", categoria:"Modalização", frase:"Apparemment, la situation s'améliore."},
  {fr:"effectivement", pt:"efetivamente, de fato", classe:"Advérbio", categoria:"Confirmação", frase:"Effectivement, les chiffres ont augmenté."},
  {fr:"sûrement", pt:"certamente", classe:"Advérbio", categoria:"Modalização", frase:"C'est sûrement la meilleure solution."},
  {fr:"notamment / surtout", pt:"notadamente / sobretudo", classe:"Advérbio", categoria:"Ênfase", frase:"Notamment chez les jeunes, ce phénomène s'accentue."},
  {fr:"autrement", pt:"de outro modo, senão", classe:"Advérbio", categoria:"Alternativa", frase:"Autrement, rien ne va changer."},
  {fr:"forcément", pt:"necessariamente, forçosamente", classe:"Advérbio", categoria:"Modalização", frase:"Ce n'est pas forcément une bonne idée."},
  {fr:"auparavant / autrefois", pt:"anteriormente, antes / antigamente", classe:"Advérbio", categoria:"Tempo", frase:"Autrefois, cette pratique était courante."},
  {fr:"désormais", pt:"a partir de agora, doravante", classe:"Advérbio", categoria:"Tempo", frase:"Désormais, il faudra agir autrement."},
  {fr:"plutôt", pt:"em vez disso, de preferência", classe:"Advérbio", categoria:"Preferência", frase:"Il vaut mieux choisir plutôt cette option."},
  {fr:"ainsi", pt:"assim, desta forma", classe:"Advérbio", categoria:"Consequência", frase:"Ainsi, on peut réduire les inégalités."},
  {fr:"constamment / en permanence", pt:"constantemente / permanentemente", classe:"Advérbio", categoria:"Frequência", frase:"Les prix augmentent constamment."},
  {fr:"à plusieurs reprises", pt:"por diversas vezes", classe:"Locução adverbial", categoria:"Frequência", frase:"Ce problème a été signalé à plusieurs reprises."},
  {fr:"certes / bien entendu", pt:"certamente / claro (concessão)", classe:"Advérbio", categoria:"Concessão", frase:"Certes, la solution n'est pas parfaite."},
  {fr:"d'avantage", pt:"mais, em maior quantidade", classe:"Advérbio", categoria:"Intensidade", frase:"Il faut investir d'avantage dans l'éducation."},

  // ---- SUBSTANTIVOS ----
  {fr:"la quête", pt:"a busca", classe:"Substantivo", categoria:"Abstrato", frase:"La quête du bonheur est universelle."},
  {fr:"nuisible / nuire", pt:"nocivo / prejudicar", classe:"Adjetivo/Verbo", categoria:"Consequência", frase:"C'est nuisible pour la santé publique."},
  {fr:"mesure", pt:"medida", classe:"Substantivo", categoria:"Solução", frase:"De nouvelles mesures ont été annoncées."},
  {fr:"enjeux / contraintes", pt:"desafios / restrições", classe:"Substantivo", categoria:"Problema", frase:"Les enjeux climatiques sont majeurs."},
  {fr:"cible / ciblé(e) / cibler", pt:"alvo / direcionado / mirar em", classe:"Substantivo/Verbo", categoria:"Solução", frase:"Cette campagne cible les jeunes adultes."},
  {fr:"troubles", pt:"transtornos, distúrbios", classe:"Substantivo", categoria:"Saúde", frase:"Cela peut entraîner des troubles psychologiques."},
  {fr:"sûreté", pt:"segurança", classe:"Substantivo", categoria:"Abstrato", frase:"La sûreté des citoyens est une priorité."},
  {fr:"accomplissement", pt:"realização, conquista", classe:"Substantivo", categoria:"Abstrato", frase:"C'est un véritable accomplissement personnel."},
  {fr:"tranche d'âge", pt:"faixa etária", classe:"Substantivo", categoria:"Dados", frase:"Toutes les tranches d'âge sont concernées."},
  {fr:"souci / soucieux de", pt:"preocupação / preocupado com", classe:"Substantivo/Adjetivo", categoria:"Argumentação", frase:"Des mesures soucieuses de l'environnement."},
  {fr:"une approche", pt:"uma abordagem", classe:"Substantivo", categoria:"Argumentação", frase:"Il faut adopter une nouvelle approche."},
  {fr:"incontournable", pt:"incontornável, indispensável", classe:"Adjetivo", categoria:"Ênfase", frase:"C'est un sujet incontournable aujourd'hui."},
  {fr:"majeur(e)", pt:"importante, de peso", classe:"Adjetivo", categoria:"Ênfase", frase:"C'est un enjeu majeur pour la société."},
  {fr:"demeure", pt:"permanece, continua a ser", classe:"Verbo", categoria:"Estado", frase:"Le problème demeure entier malgré les efforts."},
  {fr:"face à", pt:"diante de, frente a", classe:"Locução", categoria:"Introdução de argumento", frase:"Face à cette crise, il faut réagir vite."},

  // ---- EXPRESSÕES PARA OPINIÃO ----
  {fr:"selon moi / d'après moi / à mon sens / à mes yeux", pt:"na minha opinião", classe:"Expressão de opinião", categoria:"Opinião", frase:"À mes yeux, c'est la meilleure solution."},

  // ---- ESTRUTURAS GRAMATICAIS-CHAVE ----
  {fr:"il faut + infinitif", pt:"é necessário / é preciso + verbo", classe:"Estrutura impessoal", categoria:"Necessidade", frase:"Il faut étudier davantage ce phénomène."},
  {fr:"il faut que + subjonctif", pt:"é necessário que (+ subjuntivo)", classe:"Estrutura impessoal", categoria:"Necessidade", frase:"Il faut que le gouvernement agisse vite."},
  {fr:"il est important/urgent/crucial/essentiel que", pt:"é importante/urgente/crucial/essencial que", classe:"Estrutura impessoal", categoria:"Necessidade", frase:"Il est crucial que les jeunes s'informent."},
  {fr:"venir de + infinitif", pt:"acabar de (+ verbo) — passado recente", classe:"Estrutura verbal", categoria:"Tempo verbal", frase:"Je viens de me réveiller."},
  {fr:"aller + infinitif", pt:"ir (+ verbo) — futuro próximo", classe:"Estrutura verbal", categoria:"Tempo verbal", frase:"Je vais faire les lessives."},
  {fr:"être en train de + infinitif", pt:"estar (+ gerúndio) — presente contínuo", classe:"Estrutura verbal", categoria:"Tempo verbal", frase:"Je suis en train d'étudier."},
];

const VOCAB_SEED_VIDA_COTIDIANA = [
  {fr:"la famille", pt:"a família", classe:"Substantivo", categoria:"Família", frase:"Ma famille est très unie."},
  {fr:"les parents", pt:"os pais", classe:"Substantivo", categoria:"Família", frase:"Mes parents habitent à Lyon."},
  {fr:"le père", pt:"o pai", classe:"Substantivo", categoria:"Família", frase:"Mon père travaille dans une banque."},
  {fr:"la mère", pt:"a mãe", classe:"Substantivo", categoria:"Família", frase:"Ma mère est enseignante."},
  {fr:"le fils", pt:"o filho", classe:"Substantivo", categoria:"Família", frase:"Leur fils étudie la médecine."},
  {fr:"la fille", pt:"a filha", classe:"Substantivo", categoria:"Família", frase:"Sa fille a dix ans."},
  {fr:"le frère", pt:"o irmão", classe:"Substantivo", categoria:"Família", frase:"Mon frère habite à Paris."},
  {fr:"la sœur", pt:"a irmã", classe:"Substantivo", categoria:"Família", frase:"Ma sœur travaille à l'étranger."},
  {fr:"les jumeaux", pt:"os gêmeos", classe:"Substantivo", categoria:"Família", frase:"Les jumeaux se ressemblent beaucoup."},
  {fr:"les jumelles", pt:"as gêmeas", classe:"Substantivo", categoria:"Família", frase:"Les jumelles sont nées en mars."},
  {fr:"le demi-frère", pt:"o meio-irmão", classe:"Substantivo", categoria:"Família", frase:"J'ai un demi-frère plus jeune."},
  {fr:"la demi-sœur", pt:"a meia-irmã", classe:"Substantivo", categoria:"Família", frase:"Ma demi-sœur vit en Espagne."},
  {fr:"le beau-père", pt:"o padrasto / sogro", classe:"Substantivo", categoria:"Família", frase:"Mon beau-père est très gentil."},
  {fr:"la belle-mère", pt:"a madrasta / sogra", classe:"Substantivo", categoria:"Família", frase:"Ma belle-mère cuisine très bien."},
  {fr:"le beau-frère", pt:"o cunhado", classe:"Substantivo", categoria:"Família", frase:"Mon beau-frère travaille dans l'informatique."},
  {fr:"la belle-sœur", pt:"a cunhada", classe:"Substantivo", categoria:"Família", frase:"Ma belle-sœur habite en Italie."},
  {fr:"le beau-fils", pt:"o enteado / genro", classe:"Substantivo", categoria:"Família", frase:"Son beau-fils vient dîner ce soir."},
  {fr:"la belle-fille", pt:"a enteada / nora", classe:"Substantivo", categoria:"Família", frase:"Sa belle-fille est avocate."},
  {fr:"le conjoint", pt:"o cônjuge", classe:"Substantivo", categoria:"Família", frase:"Le conjoint doit signer ce document."},
  {fr:"la conjointe", pt:"a cônjuge", classe:"Substantivo", categoria:"Família", frase:"Sa conjointe travaille à l'hôpital."},
  {fr:"le partenaire", pt:"o parceiro", classe:"Substantivo", categoria:"Família", frase:"Son partenaire l'accompagne partout."},
  {fr:"la femme", pt:"a esposa, a mulher", classe:"Substantivo", categoria:"Família", frase:"Sa femme est médecin."},
  {fr:"le mari", pt:"o marido", classe:"Substantivo", categoria:"Família", frase:"Son mari est architecte."},
  {fr:"le fiancé", pt:"o noivo", classe:"Substantivo", categoria:"Família", frase:"Le fiancé a offert une bague."},
  {fr:"la fiancée", pt:"a noiva", classe:"Substantivo", categoria:"Família", frase:"La fiancée porte une robe blanche."},
  {fr:"le veuf", pt:"o viúvo", classe:"Substantivo", categoria:"Família", frase:"Le veuf vit seul depuis un an."},
  {fr:"la veuve", pt:"a viúva", classe:"Substantivo", categoria:"Família", frase:"La veuve a repris le travail de son mari."},
  {fr:"l'enfant adopté", pt:"a criança adotada", classe:"Substantivo", categoria:"Família", frase:"L'enfant adopté s'est bien intégré."},
  {fr:"les parents adoptifs", pt:"os pais adotivos", classe:"Substantivo", categoria:"Família", frase:"Les parents adoptifs l'ont accueilli avec amour."},
  {fr:"la famille recomposée", pt:"a família recomposta", classe:"Substantivo", categoria:"Família", frase:"La famille recomposée compte cinq enfants."},
  {fr:"la famille monoparentale", pt:"a família monoparental", classe:"Substantivo", categoria:"Família", frase:"La famille monoparentale fait face à plusieurs défis."},
  {fr:"la famille nombreuse", pt:"a família numerosa", classe:"Substantivo", categoria:"Família", frase:"Cette famille nombreuse a sept enfants."},
  {fr:"le tuteur", pt:"o tutor", classe:"Substantivo", categoria:"Família", frase:"Le tuteur légal signe les documents scolaires."},
  {fr:"le parrain", pt:"o padrinho", classe:"Substantivo", categoria:"Família", frase:"Le parrain a offert un cadeau au baptême."},
  {fr:"la marraine", pt:"a madrinha", classe:"Substantivo", categoria:"Família", frase:"La marraine s'occupe de sa filleule."},
  {fr:"se disputer", pt:"discutir, brigar", classe:"Verbo", categoria:"Relações Pessoais", frase:"Ils se disputent souvent pour rien."},
  {fr:"s'entendre", pt:"dar-se bem", classe:"Verbo", categoria:"Relações Pessoais", frase:"Elle s'entend très bien avec sa sœur."},
  {fr:"soutenir", pt:"apoiar", classe:"Verbo", categoria:"Relações Pessoais", frase:"Il faut soutenir ses proches dans les moments difficiles."},
  {fr:"partager", pt:"compartilhar", classe:"Verbo", categoria:"Relações Pessoais", frase:"Ils partagent les tâches ménagères."},
  {fr:"communiquer", pt:"comunicar", classe:"Verbo", categoria:"Relações Pessoais", frase:"Il est essentiel de bien communiquer en couple."},
  {fr:"faire confiance", pt:"confiar", classe:"Verbo/Locução", categoria:"Relações Pessoais", frase:"Il faut faire confiance à ses amis."},
  {fr:"rompre", pt:"romper, terminar", classe:"Verbo", categoria:"Relações Pessoais", frase:"Ils ont décidé de rompre après dix ans."},
  {fr:"pardonner", pt:"perdoar", classe:"Verbo", categoria:"Relações Pessoais", frase:"Elle a fini par lui pardonner."},
  {fr:"respecter", pt:"respeitar", classe:"Verbo", categoria:"Relações Pessoais", frase:"Il faut respecter les choix de chacun."},
  {fr:"éduquer", pt:"educar", classe:"Verbo", categoria:"Relações Pessoais", frase:"Éduquer un enfant demande de la patience."},
  {fr:"élever", pt:"criar (um filho)", classe:"Verbo", categoria:"Relações Pessoais", frase:"Élever des enfants seul n'est pas facile."},
  {fr:"transmettre des valeurs", pt:"transmitir valores", classe:"Verbo/Locução", categoria:"Relações Pessoais", frase:"Les parents transmettent des valeurs à leurs enfants."},
  {fr:"fonder une famille", pt:"constituir família", classe:"Verbo/Locução", categoria:"Relações Pessoais", frase:"Ils veulent fonder une famille l'année prochaine."},
  {fr:"vivre ensemble", pt:"viver juntos", classe:"Verbo/Locução", categoria:"Relações Pessoais", frase:"Ils vivent ensemble depuis deux ans."},
  {fr:"heureux", pt:"feliz", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il se sent heureux depuis qu'il a changé de travail."},
  {fr:"satisfait", pt:"satisfeito", classe:"Adjetivo", categoria:"Sentimentos", frase:"Elle est satisfaite de ses résultats."},
  {fr:"épanoui", pt:"realizado, pleno", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il se sent épanoui dans sa nouvelle vie."},
  {fr:"optimiste", pt:"otimista", classe:"Adjetivo", categoria:"Sentimentos", frase:"Elle reste optimiste malgré les difficultés."},
  {fr:"pessimiste", pt:"pessimista", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il est plutôt pessimiste sur l'avenir."},
  {fr:"nostalgique", pt:"nostálgico", classe:"Adjetivo", categoria:"Sentimentos", frase:"Elle devient nostalgique en écoutant cette chanson."},
  {fr:"déçu", pt:"decepcionado", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il est déçu par sa note."},
  {fr:"frustré", pt:"frustrado", classe:"Adjetivo", categoria:"Sentimentos", frase:"Elle se sent frustrée de ne pas réussir."},
  {fr:"inquiet", pt:"preocupado", classe:"Adjetivo", categoria:"Sentimentos", frase:"Je suis inquiet pour son avenir."},
  {fr:"anxieux", pt:"ansioso", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il est anxieux avant chaque examen."},
  {fr:"stressé", pt:"estressado", classe:"Adjetivo", categoria:"Sentimentos", frase:"Elle est stressée par son travail."},
  {fr:"soulagé", pt:"aliviado", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il est soulagé après les résultats."},
  {fr:"motivé", pt:"motivado", classe:"Adjetivo", categoria:"Sentimentos", frase:"Elle est très motivée pour ce projet."},
  {fr:"enthousiaste", pt:"entusiasmado", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il est enthousiaste à l'idée de voyager."},
  {fr:"passionné", pt:"apaixonado", classe:"Adjetivo", categoria:"Sentimentos", frase:"Elle est passionnée par la musique."},
  {fr:"reconnaissant", pt:"grato", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il est reconnaissant envers ses parents."},
  {fr:"jaloux", pt:"ciumento", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il est un peu jaloux de son frère."},
  {fr:"fier", pt:"orgulhoso", classe:"Adjetivo", categoria:"Sentimentos", frase:"Elle est fière de ses enfants."},
  {fr:"honteux", pt:"envergonhado", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il se sent honteux de son erreur."},
  {fr:"embarrassé", pt:"constrangido", classe:"Adjetivo", categoria:"Sentimentos", frase:"Elle était embarrassée devant tout le monde."},
  {fr:"en colère", pt:"com raiva", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il est en colère contre son collègue."},
  {fr:"calme", pt:"calmo", classe:"Adjetivo", categoria:"Sentimentos", frase:"Elle reste calme même sous pression."},
  {fr:"serein", pt:"sereno", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il aborde l'avenir de façon sereine."},
  {fr:"ému", pt:"emocionado", classe:"Adjetivo", categoria:"Sentimentos", frase:"Elle était émue pendant le discours."},
  {fr:"surpris", pt:"surpreso", classe:"Adjetivo", categoria:"Sentimentos", frase:"Il a été surpris par la nouvelle."},
  {fr:"généreux", pt:"generoso", classe:"Adjetivo", categoria:"Qualidades", frase:"C'est quelqu'un de très généreux."},
  {fr:"bienveillant", pt:"bondoso", classe:"Adjetivo", categoria:"Qualidades", frase:"Son professeur est très bienveillant."},
  {fr:"empathique", pt:"empático", classe:"Adjetivo", categoria:"Qualidades", frase:"Elle est très empathique envers ses collègues."},
  {fr:"ambitieux", pt:"ambicioso", classe:"Adjetivo", categoria:"Qualidades", frase:"Il est ambitieux dans sa carrière."},
  {fr:"responsable", pt:"responsável", classe:"Adjetivo", categoria:"Qualidades", frase:"C'est une personne très responsable."},
  {fr:"organisé", pt:"organizado", classe:"Adjetivo", categoria:"Qualidades", frase:"Il est toujours très organisé."},
  {fr:"ponctuel", pt:"pontual", classe:"Adjetivo", categoria:"Qualidades", frase:"Elle est ponctuelle à chaque rendez-vous."},
  {fr:"fiable", pt:"confiável", classe:"Adjetivo", categoria:"Qualidades", frase:"C'est un collègue fiable."},
  {fr:"créatif", pt:"criativo", classe:"Adjetivo", categoria:"Qualidades", frase:"Il est créatif dans son travail."},
  {fr:"sociable", pt:"sociável", classe:"Adjetivo", categoria:"Qualidades", frase:"Elle est très sociable avec tout le monde."},
  {fr:"travailleur", pt:"trabalhador", classe:"Adjetivo", categoria:"Qualidades", frase:"C'est un employé travailleur."},
  {fr:"paresseux", pt:"preguiçoso", classe:"Adjetivo", categoria:"Defeitos", frase:"Il est un peu paresseux le matin."},
  {fr:"égoïste", pt:"egoísta", classe:"Adjetivo", categoria:"Defeitos", frase:"Elle peut être égoïste parfois."},
  {fr:"impatient", pt:"impaciente", classe:"Adjetivo", categoria:"Defeitos", frase:"Il est impatient dans les files d'attente."},
  {fr:"impulsif", pt:"impulsivo", classe:"Adjetivo", categoria:"Defeitos", frase:"Elle prend des décisions impulsives."},
  {fr:"arrogant", pt:"arrogante", classe:"Adjetivo", categoria:"Defeitos", frase:"Il se montre arrogant avec ses collègues."},
  {fr:"désorganisé", pt:"desorganizado", classe:"Adjetivo", categoria:"Defeitos", frase:"Son bureau est toujours désorganisé."},
  {fr:"susceptible", pt:"suscetível, sensível", classe:"Adjetivo", categoria:"Defeitos", frase:"Il est susceptible face à la critique."},
  {fr:"timide", pt:"tímido", classe:"Adjetivo", categoria:"Defeitos", frase:"Il est timide avec les inconnus."},
  {fr:"réservé", pt:"reservado", classe:"Adjetivo", categoria:"Defeitos", frase:"Elle est plutôt réservée en public."},
  {fr:"spacieux", pt:"espaçoso", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"L'appartement est spacieux et lumineux."},
  {fr:"exigu", pt:"exíguo, apertado", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"Le studio est un peu exigu."},
  {fr:"lumineux", pt:"luminoso", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"Le salon est très lumineux."},
  {fr:"sombre", pt:"sombrio, escuro", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"La cave est sombre et froide."},
  {fr:"bruyant", pt:"barulhento", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"La rue est bruyante à cause du trafic."},
  {fr:"animé", pt:"animado, movimentado", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"Le centre-ville est très animé le week-end."},
  {fr:"résidentiel", pt:"residencial", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"C'est un quartier résidentiel tranquille."},
  {fr:"touristique", pt:"turístico", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"Le village est très touristique en été."},
  {fr:"accueillant", pt:"acolhedor", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"L'hôtel est petit mais accueillant."},
  {fr:"moderne", pt:"moderno", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"Le bâtiment est très moderne."},
  {fr:"ancien", pt:"antigo", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"Le quartier ancien attire les touristes."},
  {fr:"confortable", pt:"confortável", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"L'appartement est confortable et bien chauffé."},
  {fr:"propre", pt:"limpo", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"La ville est propre et bien entretenue."},
  {fr:"sale", pt:"sujo", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"La rue était sale après le marché."},
  {fr:"sécurisé", pt:"seguro", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"C'est un quartier sécurisé la nuit."},
  {fr:"dangereux", pt:"perigoso", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"Certaines rues sont dangereuses la nuit."},
  {fr:"verdoyant", pt:"verdejante", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"Le parc est très verdoyant au printemps."},
  {fr:"pollué", pt:"poluído", classe:"Adjetivo", categoria:"Descrever um Lugar", frase:"L'air est pollué en centre-ville."},
  {fr:"une maison", pt:"uma casa", classe:"Substantivo", categoria:"Moradia", frase:"Ils habitent une maison avec jardin."},
  {fr:"un appartement", pt:"um apartamento", classe:"Substantivo", categoria:"Moradia", frase:"Il loue un appartement au centre-ville."},
  {fr:"une résidence", pt:"uma residência", classe:"Substantivo", categoria:"Moradia", frase:"La résidence dispose d'une piscine."},
  {fr:"une colocation", pt:"uma república (moradia compartilhada)", classe:"Substantivo", categoria:"Moradia", frase:"Elle vit en colocation avec deux amis."},
  {fr:"une maison de retraite", pt:"um asilo, uma casa de repouso", classe:"Substantivo", categoria:"Moradia", frase:"Sa grand-mère vit dans une maison de retraite."},
  {fr:"une résidence étudiante", pt:"uma residência estudantil", classe:"Substantivo", categoria:"Moradia", frase:"Il habite en résidence étudiante près de la fac."},
  {fr:"un logement social", pt:"uma moradia social", classe:"Substantivo", categoria:"Moradia", frase:"Ils ont obtenu un logement social l'an dernier."},
  {fr:"le salon", pt:"a sala de estar", classe:"Substantivo", categoria:"Cômodos da Casa", frase:"Toute la famille se retrouve dans le salon."},
  {fr:"la cuisine", pt:"a cozinha", classe:"Substantivo", categoria:"Cômodos da Casa", frase:"La cuisine est équipée et moderne."},
  {fr:"la chambre", pt:"o quarto", classe:"Substantivo", categoria:"Cômodos da Casa", frase:"Sa chambre donne sur le jardin."},
  {fr:"la salle de bains", pt:"o banheiro", classe:"Substantivo", categoria:"Cômodos da Casa", frase:"La salle de bains vient d'être refaite."},
  {fr:"le bureau", pt:"o escritório", classe:"Substantivo", categoria:"Cômodos da Casa", frase:"Il travaille dans son bureau à la maison."},
  {fr:"le balcon", pt:"a varanda", classe:"Substantivo", categoria:"Cômodos da Casa", frase:"On prend le café sur le balcon."},
  {fr:"la terrasse", pt:"o terraço", classe:"Substantivo", categoria:"Cômodos da Casa", frase:"La terrasse offre une belle vue."},
  {fr:"le garage", pt:"a garagem", classe:"Substantivo", categoria:"Cômodos da Casa", frase:"La voiture est garée dans le garage."},
  {fr:"la cave", pt:"o porão", classe:"Substantivo", categoria:"Cômodos da Casa", frase:"On garde le vin à la cave."},
  {fr:"le grenier", pt:"o sótão", classe:"Substantivo", categoria:"Cômodos da Casa", frase:"Les vieux meubles sont rangés au grenier."},
  {fr:"le canapé", pt:"o sofá", classe:"Substantivo", categoria:"Móveis", frase:"Le canapé est très confortable."},
  {fr:"le fauteuil", pt:"a poltrona", classe:"Substantivo", categoria:"Móveis", frase:"Il lit toujours dans son fauteuil."},
  {fr:"la chaise", pt:"a cadeira", classe:"Substantivo", categoria:"Móveis", frase:"La chaise est cassée."},
  {fr:"la table", pt:"a mesa", classe:"Substantivo", categoria:"Móveis", frase:"La table est mise pour le dîner."},
  {fr:"le lit", pt:"a cama", classe:"Substantivo", categoria:"Móveis", frase:"Le lit est près de la fenêtre."},
  {fr:"la commode", pt:"a cômoda", classe:"Substantivo", categoria:"Móveis", frase:"Les vêtements sont dans la commode."},
  {fr:"l'armoire", pt:"o armário, guarda-roupa", classe:"Substantivo", categoria:"Móveis", frase:"L'armoire est pleine de vêtements."},
  {fr:"le placard", pt:"o armário embutido", classe:"Substantivo", categoria:"Móveis", frase:"La vaisselle est rangée dans le placard."},
  {fr:"la bibliothèque", pt:"a estante de livros", classe:"Substantivo", categoria:"Móveis", frase:"La bibliothèque déborde de livres."},
  {fr:"l'étagère", pt:"a prateleira", classe:"Substantivo", categoria:"Móveis", frase:"Les livres sont sur l'étagère."},
  {fr:"le miroir", pt:"o espelho", classe:"Substantivo", categoria:"Móveis", frase:"Le miroir est accroché dans l'entrée."},
  {fr:"la lampe", pt:"a luminária", classe:"Substantivo", categoria:"Móveis", frase:"La lampe éclaire toute la pièce."},
  {fr:"le tapis", pt:"o tapete", classe:"Substantivo", categoria:"Móveis", frase:"Le tapis est au milieu du salon."},
  {fr:"le rideau", pt:"a cortina", classe:"Substantivo", categoria:"Móveis", frase:"Le rideau bloque la lumière du matin."},
  {fr:"faire le ménage", pt:"fazer a limpeza da casa", classe:"Verbo/Locução", categoria:"Tarefas Domésticas", frase:"Elle fait le ménage tous les samedis."},
  {fr:"passer l'aspirateur", pt:"passar aspirador", classe:"Verbo/Locução", categoria:"Tarefas Domésticas", frase:"Il passe l'aspirateur dans le salon."},
  {fr:"balayer", pt:"varrer", classe:"Verbo", categoria:"Tarefas Domésticas", frase:"Elle balaie la cuisine chaque soir."},
  {fr:"laver le sol", pt:"lavar o chão", classe:"Verbo/Locução", categoria:"Tarefas Domésticas", frase:"Il lave le sol de la cuisine."},
  {fr:"faire la vaisselle", pt:"lavar a louça", classe:"Verbo/Locução", categoria:"Tarefas Domésticas", frase:"C'est son tour de faire la vaisselle."},
  {fr:"faire la lessive", pt:"lavar a roupa", classe:"Verbo/Locução", categoria:"Tarefas Domésticas", frase:"Elle fait la lessive le dimanche."},
  {fr:"repasser", pt:"passar roupa (ferro)", classe:"Verbo", categoria:"Tarefas Domésticas", frase:"Il déteste repasser les chemises."},
  {fr:"plier le linge", pt:"dobrar a roupa", classe:"Verbo/Locução", categoria:"Tarefas Domésticas", frase:"Elle plie le linge devant la télé."},
  {fr:"sortir les poubelles", pt:"tirar o lixo", classe:"Verbo/Locução", categoria:"Tarefas Domésticas", frase:"C'est à toi de sortir les poubelles."},
  {fr:"recycler", pt:"reciclar", classe:"Verbo", categoria:"Tarefas Domésticas", frase:"Ils recyclent le verre et le papier."},
  {fr:"cuisiner", pt:"cozinhar", classe:"Verbo", categoria:"Tarefas Domésticas", frase:"Elle adore cuisiner le week-end."},
  {fr:"préparer le repas", pt:"preparar a refeição", classe:"Verbo/Locução", categoria:"Tarefas Domésticas", frase:"Il prépare le repas pour toute la famille."},
  {fr:"faire les courses", pt:"fazer compras", classe:"Verbo/Locução", categoria:"Tarefas Domésticas", frase:"Elle fait les courses au marché."},
  {fr:"ranger", pt:"arrumar, guardar", classe:"Verbo", categoria:"Tarefas Domésticas", frase:"Il range sa chambre avant de sortir."},
  {fr:"nettoyer les vitres", pt:"limpar as janelas/vidros", classe:"Verbo/Locução", categoria:"Tarefas Domésticas", frase:"Elle nettoie les vitres une fois par mois."},
  {fr:"faire son lit", pt:"arrumar a cama", classe:"Verbo/Locução", categoria:"Tarefas Domésticas", frase:"Il fait son lit tous les matins."},
  {fr:"la ville", pt:"a cidade", classe:"Substantivo", categoria:"Cidade", frase:"La ville s'est beaucoup développée."},
  {fr:"le quartier", pt:"o bairro", classe:"Substantivo", categoria:"Cidade", frase:"Il a grandi dans ce quartier."},
  {fr:"le centre-ville", pt:"o centro da cidade", classe:"Substantivo", categoria:"Cidade", frase:"Le centre-ville est piéton le dimanche."},
  {fr:"la banlieue", pt:"a periferia, subúrbio", classe:"Substantivo", categoria:"Cidade", frase:"Elle habite en banlieue parisienne."},
  {fr:"la mairie", pt:"a prefeitura", classe:"Substantivo", categoria:"Cidade", frase:"Le mariage a lieu à la mairie."},
  {fr:"la gare", pt:"a estação (de trem)", classe:"Substantivo", categoria:"Cidade", frase:"Il attend son train à la gare."},
  {fr:"le métro", pt:"o metrô", classe:"Substantivo", categoria:"Cidade", frase:"Elle prend le métro tous les jours."},
  {fr:"le tramway", pt:"o bonde, VLT", classe:"Substantivo", categoria:"Cidade", frase:"Le tramway relie les deux quartiers."},
  {fr:"le rond-point", pt:"a rotatória", classe:"Substantivo", categoria:"Cidade", frase:"Tournez à droite après le rond-point."},
  {fr:"le feu tricolore", pt:"o semáforo", classe:"Substantivo", categoria:"Cidade", frase:"La voiture s'arrête au feu tricolore."},
  {fr:"le trottoir", pt:"a calçada", classe:"Substantivo", categoria:"Cidade", frase:"Les piétons marchent sur le trottoir."},
  {fr:"la piste cyclable", pt:"a ciclovia", classe:"Substantivo", categoria:"Cidade", frase:"Il roule sur la piste cyclable."},
  {fr:"la zone piétonne", pt:"a área de pedestres", classe:"Substantivo", categoria:"Cidade", frase:"La zone piétonne est très fréquentée."},
  {fr:"les transports en commun", pt:"o transporte público", classe:"Substantivo", categoria:"Cidade", frase:"Elle utilise les transports en commun tous les jours."},
  {fr:"les embouteillages", pt:"os engarrafamentos", classe:"Substantivo", categoria:"Cidade", frase:"Les embouteillages augmentent chaque année."},
  {fr:"la mobilité urbaine", pt:"a mobilidade urbana", classe:"Substantivo", categoria:"Cidade", frase:"La mobilité urbaine est un vrai défi."},
  {fr:"le covoiturage", pt:"a carona compartilhada", classe:"Substantivo", categoria:"Cidade", frase:"Ils font du covoiturage pour aller au travail."},
  {fr:"le réchauffement climatique", pt:"o aquecimento global", classe:"Substantivo", categoria:"Aquecimento Global", frase:"Le réchauffement climatique inquiète les scientifiques."},
  {fr:"le changement climatique", pt:"a mudança climática", classe:"Substantivo", categoria:"Aquecimento Global", frase:"Le changement climatique affecte toute la planète."},
  {fr:"l'effet de serre", pt:"o efeito estufa", classe:"Substantivo", categoria:"Aquecimento Global", frase:"L'effet de serre aggrave le réchauffement."},
  {fr:"les émissions de CO₂", pt:"as emissões de CO₂", classe:"Substantivo", categoria:"Aquecimento Global", frase:"Il faut réduire les émissions de CO₂."},
  {fr:"les combustibles fossiles", pt:"os combustíveis fósseis", classe:"Substantivo", categoria:"Aquecimento Global", frase:"Les combustibles fossiles polluent l'atmosphère."},
  {fr:"la transition énergétique", pt:"a transição energética", classe:"Substantivo", categoria:"Aquecimento Global", frase:"La transition énergétique est indispensable."},
  {fr:"la pollution atmosphérique", pt:"a poluição atmosférica", classe:"Substantivo", categoria:"Poluição", frase:"La pollution atmosphérique nuit à la santé."},
  {fr:"la pollution sonore", pt:"a poluição sonora", classe:"Substantivo", categoria:"Poluição", frase:"La pollution sonore perturbe le sommeil."},
  {fr:"la pollution lumineuse", pt:"a poluição luminosa", classe:"Substantivo", categoria:"Poluição", frase:"La pollution lumineuse gêne l'observation des étoiles."},
  {fr:"la pollution visuelle", pt:"a poluição visual", classe:"Substantivo", categoria:"Poluição", frase:"Les panneaux publicitaires créent une pollution visuelle."},
  {fr:"la pollution plastique", pt:"a poluição plástica", classe:"Substantivo", categoria:"Poluição", frase:"La pollution plastique menace les océans."},
  {fr:"la pollution marine", pt:"a poluição marinha", classe:"Substantivo", categoria:"Poluição", frase:"La pollution marine tue de nombreux animaux."},
  {fr:"la pollution des sols", pt:"a poluição do solo", classe:"Substantivo", categoria:"Poluição", frase:"La pollution des sols réduit les rendements agricoles."},
  {fr:"la pollution de l'eau", pt:"a poluição da água", classe:"Substantivo", categoria:"Poluição", frase:"La pollution de l'eau limite l'accès à l'eau potable."},
  {fr:"la pollution industrielle", pt:"a poluição industrial", classe:"Substantivo", categoria:"Poluição", frase:"La pollution industrielle touche les zones urbaines."},
  {fr:"trier", pt:"separar, triar (o lixo)", classe:"Verbo", categoria:"Resíduos", frase:"Il faut trier les déchets avant de les jeter."},
  {fr:"réutiliser", pt:"reutilizar", classe:"Verbo", categoria:"Resíduos", frase:"On peut réutiliser certains emballages."},
  {fr:"réduire", pt:"reduzir", classe:"Verbo", categoria:"Resíduos", frase:"Il faut réduire notre production de déchets."},
  {fr:"l'économie circulaire", pt:"a economia circular", classe:"Substantivo", categoria:"Resíduos", frase:"L'économie circulaire limite le gaspillage."},
  {fr:"l'obsolescence programmée", pt:"a obsolescência programada", classe:"Substantivo", categoria:"Resíduos", frase:"L'obsolescence programmée pousse à la surconsommation."},
  {fr:"le consumérisme", pt:"o consumismo", classe:"Substantivo", categoria:"Consumo", frase:"Le consumérisme influence nos habitudes d'achat."},
  {fr:"la surconsommation", pt:"o consumo excessivo", classe:"Substantivo", categoria:"Consumo", frase:"La surconsommation épuise les ressources naturelles."},
  {fr:"la fast fashion", pt:"a moda rápida", classe:"Substantivo", categoria:"Consumo", frase:"La fast fashion pollue énormément."},
  {fr:"la mode éphémère", pt:"a moda efêmera", classe:"Substantivo", categoria:"Consumo", frase:"La mode éphémère encourage le gaspillage."},
  {fr:"les vêtements de marque", pt:"as roupas de marca", classe:"Substantivo", categoria:"Consumo", frase:"Il préfère les vêtements de marque."},
  {fr:"les vêtements d'occasion", pt:"as roupas de segunda mão", classe:"Substantivo", categoria:"Consumo", frase:"Elle achète surtout des vêtements d'occasion."},
  {fr:"une friperie", pt:"um brechó", classe:"Substantivo", categoria:"Consumo", frase:"Elle a trouvé une veste dans une friperie."},
  {fr:"une brocante", pt:"um mercado de antiguidades/pulgas", classe:"Substantivo", categoria:"Consumo", frase:"Ils ont visité une brocante ce week-end."},
  {fr:"les objets de seconde main", pt:"os objetos de segunda mão", classe:"Substantivo", categoria:"Consumo", frase:"Il vend des objets de seconde main en ligne."},
  {fr:"les produits biologiques", pt:"os produtos orgânicos", classe:"Substantivo", categoria:"Consumo", frase:"Elle achète des produits biologiques au marché."},
  {fr:"les produits en vrac", pt:"os produtos a granel", classe:"Substantivo", categoria:"Consumo", frase:"Il achète des produits en vrac pour réduire les déchets."},
  {fr:"le commerce équitable", pt:"o comércio justo", classe:"Substantivo", categoria:"Consumo", frase:"Le commerce équitable garantit un revenu juste."},
  {fr:"acheter d'occasion", pt:"comprar de segunda mão", classe:"Verbo/Locução", categoria:"Consumo", frase:"Elle préfère acheter d'occasion pour économiser."},
  {fr:"la sécurité alimentaire", pt:"a segurança alimentar", classe:"Substantivo", categoria:"Segurança Alimentar", frase:"La sécurité alimentaire reste un défi mondial."},
  {fr:"la malnutrition", pt:"a desnutrição", classe:"Substantivo", categoria:"Segurança Alimentar", frase:"La malnutrition touche encore des millions d'enfants."},
  {fr:"la famine", pt:"a fome (extrema)", classe:"Substantivo", categoria:"Segurança Alimentar", frase:"La famine frappe plusieurs régions du monde."},
  {fr:"le gaspillage alimentaire", pt:"o desperdício de alimentos", classe:"Substantivo", categoria:"Segurança Alimentar", frase:"Le gaspillage alimentaire est un problème majeur."},
  {fr:"les produits ultra-transformés", pt:"os produtos ultraprocessados", classe:"Substantivo", categoria:"Segurança Alimentar", frase:"Les produits ultra-transformés nuisent à la santé."},
  {fr:"l'agriculture biologique", pt:"a agricultura orgânica", classe:"Substantivo", categoria:"Segurança Alimentar", frase:"L'agriculture biologique évite les produits chimiques."},
  {fr:"les engrais", pt:"os fertilizantes", classe:"Substantivo", categoria:"Segurança Alimentar", frase:"Les engrais augmentent le rendement des cultures."},
  {fr:"les pesticides", pt:"os pesticidas, agrotóxicos", classe:"Substantivo", categoria:"Segurança Alimentar", frase:"Les pesticides sont nocifs pour la biodiversité."},
  {fr:"les animaux de compagnie", pt:"os animais de estimação", classe:"Substantivo", categoria:"Animais", frase:"Les animaux de compagnie apportent du réconfort."},
  {fr:"les animaux domestiques", pt:"os animais domésticos", classe:"Substantivo", categoria:"Animais", frase:"Les animaux domestiques vivent près de l'homme."},
  {fr:"les animaux sauvages", pt:"os animais selvagens", classe:"Substantivo", categoria:"Animais", frase:"Les animaux sauvages perdent leur habitat."},
  {fr:"le parc zoologique", pt:"o zoológico", classe:"Substantivo", categoria:"Animais", frase:"Ils ont visité le parc zoologique dimanche."},
  {fr:"le bien-être animal", pt:"o bem-estar animal", classe:"Substantivo", categoria:"Animais", frase:"Le bien-être animal est de plus en plus discuté."},
  {fr:"l'expérimentation animale", pt:"a experimentação animal", classe:"Substantivo", categoria:"Animais", frase:"L'expérimentation animale reste très controversée."},
  {fr:"la corrida", pt:"a tourada", classe:"Substantivo", categoria:"Animais", frase:"La corrida est interdite dans plusieurs pays."},
  {fr:"la chasse", pt:"a caça", classe:"Substantivo", categoria:"Animais", frase:"La chasse est réglementée en France."},
  {fr:"le trafic d'animaux", pt:"o tráfico de animais", classe:"Substantivo", categoria:"Animais", frase:"Le trafic d'animaux menace des espèces entières."},
  {fr:"l'école à la maison", pt:"o ensino domiciliar", classe:"Substantivo", categoria:"Escola", frase:"De plus en plus de familles choisissent l'école à la maison."},
  {fr:"l'école publique", pt:"a escola pública", classe:"Substantivo", categoria:"Escola", frase:"Il a étudié dans l'école publique de son quartier."},
  {fr:"l'école privée", pt:"a escola particular", classe:"Substantivo", categoria:"Escola", frase:"Ils ont inscrit leur fille dans une école privée."},
  {fr:"les devoirs", pt:"os deveres de casa", classe:"Substantivo", categoria:"Escola", frase:"Il fait ses devoirs après le dîner."},
  {fr:"l'uniforme scolaire", pt:"o uniforme escolar", classe:"Substantivo", categoria:"Escola", frase:"L'uniforme scolaire est obligatoire dans cette école."},
  {fr:"les études", pt:"os estudos", classe:"Substantivo", categoria:"Escola", frase:"Elle poursuit ses études à l'université."},
  {fr:"les compétences", pt:"as competências, habilidades", classe:"Substantivo", categoria:"Escola", frase:"Ce poste demande des compétences spécifiques."},
  {fr:"les connaissances", pt:"os conhecimentos", classe:"Substantivo", categoria:"Escola", frase:"Il a de solides connaissances en mathématiques."},
  {fr:"la réussite scolaire", pt:"o sucesso escolar", classe:"Substantivo", categoria:"Escola", frase:"La réussite scolaire dépend de plusieurs facteurs."},
  {fr:"le marché du travail", pt:"o mercado de trabalho", classe:"Substantivo", categoria:"Trabalho", frase:"Le marché du travail a beaucoup changé."},
  {fr:"le chômage", pt:"o desemprego", classe:"Substantivo", categoria:"Trabalho", frase:"Le chômage a augmenté cette année."},
  {fr:"le sous-emploi", pt:"o subemprego", classe:"Substantivo", categoria:"Trabalho", frase:"Le sous-emploi touche surtout les jeunes."},
  {fr:"l'emploi", pt:"o emprego", classe:"Substantivo", categoria:"Trabalho", frase:"Il cherche un emploi depuis six mois."},
  {fr:"le télétravail", pt:"o teletrabalho, home office", classe:"Substantivo", categoria:"Trabalho", frase:"Le télétravail s'est développé depuis la pandémie."},
  {fr:"le travail hybride", pt:"o trabalho híbrido", classe:"Substantivo", categoria:"Trabalho", frase:"Elle préfère le travail hybride."},
  {fr:"le travail intérimaire", pt:"o trabalho temporário", classe:"Substantivo", categoria:"Trabalho", frase:"Il fait du travail intérimaire en attendant un CDI."},
  {fr:"l'ubérisation", pt:"a uberização", classe:"Substantivo", categoria:"Trabalho", frase:"L'ubérisation transforme certains secteurs."},
  {fr:"la précarité", pt:"a precariedade", classe:"Substantivo", categoria:"Trabalho", frase:"La précarité touche de nombreux travailleurs."},
  {fr:"le CDI", pt:"o contrato por tempo indeterminado", classe:"Substantivo", categoria:"Trabalho", frase:"Il vient de signer un CDI."},
  {fr:"le CDD", pt:"o contrato por tempo determinado", classe:"Substantivo", categoria:"Trabalho", frase:"Son CDD se termine en juin."},
  {fr:"la retraite", pt:"a aposentadoria", classe:"Substantivo", categoria:"Trabalho", frase:"Il part à la retraite l'année prochaine."},
  {fr:"la pension", pt:"a pensão", classe:"Substantivo", categoria:"Trabalho", frase:"Sa pension ne suffit pas à couvrir ses dépenses."},
  {fr:"les seniors", pt:"os idosos, seniores", classe:"Substantivo", categoria:"Trabalho", frase:"Les seniors restent actifs plus longtemps."},
  {fr:"le vieillissement de la population", pt:"o envelhecimento da população", classe:"Substantivo", categoria:"Trabalho", frase:"Le vieillissement de la population inquiète les économistes."},
  {fr:"la reconversion professionnelle", pt:"a reconversão profissional", classe:"Substantivo", categoria:"Trabalho", frase:"Elle a fait une reconversion professionnelle à quarante ans."},
  {fr:"le burn-out", pt:"a síndrome de burnout", classe:"Substantivo", categoria:"Trabalho", frase:"Il a fait un burn-out l'an dernier."},
  {fr:"le droit à la déconnexion", pt:"o direito à desconexão", classe:"Substantivo", categoria:"Trabalho", frase:"Le droit à la déconnexion protège les salariés."},
  {fr:"l'intelligence artificielle", pt:"a inteligência artificial", classe:"Substantivo", categoria:"Tecnologia", frase:"L'intelligence artificielle transforme le monde du travail."},
  {fr:"l'automatisation", pt:"a automação", classe:"Substantivo", categoria:"Tecnologia", frase:"L'automatisation remplace certains emplois."},
  {fr:"les écrans", pt:"as telas", classe:"Substantivo", categoria:"Tecnologia", frase:"Les enfants passent trop de temps devant les écrans."},
  {fr:"les réseaux sociaux", pt:"as redes sociais", classe:"Substantivo", categoria:"Tecnologia", frase:"Les réseaux sociaux influencent l'opinion publique."},
  {fr:"la cybersécurité", pt:"a cibersegurança", classe:"Substantivo", categoria:"Tecnologia", frase:"La cybersécurité est essentielle pour les entreprises."},
  {fr:"les données personnelles", pt:"os dados pessoais", classe:"Substantivo", categoria:"Tecnologia", frase:"Les données personnelles doivent être protégées."},
  {fr:"la vie privée", pt:"a privacidade", classe:"Substantivo", categoria:"Tecnologia", frase:"Internet menace parfois la vie privée."},
  {fr:"l'algorithme", pt:"o algoritmo", classe:"Substantivo", categoria:"Tecnologia", frase:"L'algorithme recommande des vidéos similaires."},
  {fr:"la désinformation", pt:"a desinformação", classe:"Substantivo", categoria:"Tecnologia", frase:"La désinformation se propage vite en ligne."},
  {fr:"les fausses informations", pt:"as informações falsas", classe:"Substantivo", categoria:"Tecnologia", frase:"Les fausses informations circulent sur les réseaux sociaux."},
  {fr:"la santé", pt:"a saúde", classe:"Substantivo", categoria:"Saúde e Bem-Estar", frase:"La santé passe avant tout."},
  {fr:"la santé mentale", pt:"a saúde mental", classe:"Substantivo", categoria:"Saúde e Bem-Estar", frase:"La santé mentale est enfin prise au sérieux."},
  {fr:"les troubles alimentaires", pt:"os transtornos alimentares", classe:"Substantivo", categoria:"Saúde e Bem-Estar", frase:"Les troubles alimentaires touchent surtout les jeunes."},
  {fr:"l'obésité", pt:"a obesidade", classe:"Substantivo", categoria:"Saúde e Bem-Estar", frase:"L'obésité augmente dans plusieurs pays."},
  {fr:"l'anorexie", pt:"a anorexia", classe:"Substantivo", categoria:"Saúde e Bem-Estar", frase:"L'anorexie nécessite un suivi médical."},
  {fr:"la boulimie", pt:"a bulimia", classe:"Substantivo", categoria:"Saúde e Bem-Estar", frase:"La boulimie reste souvent cachée."},
  {fr:"la restauration rapide", pt:"a comida rápida (fast food)", classe:"Substantivo", categoria:"Saúde e Bem-Estar", frase:"Il mange trop souvent de la restauration rapide."},
  {fr:"une alimentation équilibrée", pt:"uma alimentação equilibrada", classe:"Substantivo", categoria:"Saúde e Bem-Estar", frase:"Une alimentation équilibrée prévient de nombreuses maladies."},
  {fr:"la discrimination", pt:"a discriminação", classe:"Substantivo", categoria:"Discriminação", frase:"La discrimination reste un problème actuel."},
  {fr:"le racisme", pt:"o racismo", classe:"Substantivo", categoria:"Discriminação", frase:"Le racisme doit être combattu à l'école."},
  {fr:"le sexisme", pt:"o sexismo", classe:"Substantivo", categoria:"Discriminação", frase:"Le sexisme persiste dans le monde du travail."},
  {fr:"l'âgisme", pt:"o etarismo", classe:"Substantivo", categoria:"Discriminação", frase:"L'âgisme touche les seniors sur le marché du travail."},
  {fr:"le validisme", pt:"o capacitismo", classe:"Substantivo", categoria:"Discriminação", frase:"Le validisme exclut les personnes handicapées."},
  {fr:"la grossophobie", pt:"a gordofobia", classe:"Substantivo", categoria:"Discriminação", frase:"La grossophobie est encore banalisée."},
  {fr:"l'homophobie", pt:"a homofobia", classe:"Substantivo", categoria:"Discriminação", frase:"L'homophobie reste présente dans certains milieux."},
  {fr:"la transphobie", pt:"a transfobia", classe:"Substantivo", categoria:"Discriminação", frase:"La transphobie touche la communauté trans."},
  {fr:"la xénophobie", pt:"a xenofobia", classe:"Substantivo", categoria:"Discriminação", frase:"La xénophobie augmente en période de crise."},
  {fr:"les droits de l'homme", pt:"os direitos humanos", classe:"Substantivo", categoria:"Direitos Humanos", frase:"Les droits de l'homme doivent être protégés partout."},
  {fr:"les droits universels de l'homme", pt:"os direitos universais do homem", classe:"Substantivo", categoria:"Direitos Humanos", frase:"Les droits universels de l'homme datent de 1948."},
  {fr:"la liberté d'expression", pt:"a liberdade de expressão", classe:"Substantivo", categoria:"Direitos Humanos", frase:"La liberté d'expression est un droit fondamental."},
  {fr:"l'égalité", pt:"a igualdade", classe:"Substantivo", categoria:"Direitos Humanos", frase:"L'égalité entre les citoyens est un idéal démocratique."},
  {fr:"la fraternité", pt:"a fraternidade", classe:"Substantivo", categoria:"Direitos Humanos", frase:"La fraternité fait partie de la devise française."},
  {fr:"la dignité humaine", pt:"a dignidade humana", classe:"Substantivo", categoria:"Direitos Humanos", frase:"La dignité humaine doit toujours être respectée."},
  {fr:"la justice sociale", pt:"a justiça social", classe:"Substantivo", categoria:"Direitos Humanos", frase:"La justice sociale reste un objectif à atteindre."},
  {fr:"la solidarité", pt:"a solidariedade", classe:"Substantivo", categoria:"Direitos Humanos", frase:"La solidarité s'est renforcée pendant la crise."},
  {fr:"l'inclusion", pt:"a inclusão", classe:"Substantivo", categoria:"Direitos Humanos", frase:"L'inclusion des personnes handicapées progresse."},
  {fr:"les quotas", pt:"as cotas", classe:"Substantivo", categoria:"Igualdade", frase:"Les quotas visent à corriger certaines inégalités."},
  {fr:"les quotas en politique", pt:"as cotas na política", classe:"Substantivo", categoria:"Igualdade", frase:"Les quotas en politique favorisent la parité."},
  {fr:"la parité", pt:"a paridade", classe:"Substantivo", categoria:"Igualdade", frase:"La parité progresse lentement en politique."},
  {fr:"l'égalité femmes-hommes", pt:"a igualdade entre homens e mulheres", classe:"Substantivo", categoria:"Igualdade", frase:"L'égalité femmes-hommes reste à conquérir."},
  {fr:"les stéréotypes de genre", pt:"os estereótipos de gênero", classe:"Substantivo", categoria:"Igualdade", frase:"Les stéréotypes de genre influencent les choix professionnels."},
  {fr:"les personnes âgées", pt:"as pessoas idosas", classe:"Substantivo", categoria:"Pessoas Idosas", frase:"Les personnes âgées ont besoin de plus d'attention."},
  {fr:"le vieillissement", pt:"o envelhecimento", classe:"Substantivo", categoria:"Pessoas Idosas", frase:"Le vieillissement de la population s'accélère."},
  {fr:"la dépendance", pt:"a dependência (falta de autonomia)", classe:"Substantivo", categoria:"Pessoas Idosas", frase:"La dépendance touche de nombreuses personnes âgées."},
  {fr:"la sécurité sociale", pt:"a previdência, seguridade social", classe:"Substantivo", categoria:"Pessoas Idosas", frase:"La sécurité sociale couvre une partie des frais médicaux."},
  {fr:"le FOMO", pt:"o medo de ficar de fora (Fear Of Missing Out)", classe:"Substantivo", categoria:"Psicologia", frase:"Le FOMO pousse à rester connecté en permanence."},
  {fr:"la nomophobie", pt:"a nomofobia (medo de ficar sem celular)", classe:"Substantivo", categoria:"Psicologia", frase:"La nomophobie touche surtout les jeunes."},
  {fr:"l'addiction aux écrans", pt:"o vício em telas", classe:"Substantivo", categoria:"Psicologia", frase:"L'addiction aux écrans inquiète les parents."},
  {fr:"l'estime de soi", pt:"a autoestima", classe:"Substantivo", categoria:"Psicologia", frase:"Le sport améliore l'estime de soi."},
  {fr:"la confiance en soi", pt:"a autoconfiança", classe:"Substantivo", categoria:"Psicologia", frase:"La confiance en soi se construit avec le temps."},
  {fr:"la pression sociale", pt:"a pressão social", classe:"Substantivo", categoria:"Psicologia", frase:"La pression sociale pousse à la surconsommation."},
  {fr:"l'influence des réseaux sociaux", pt:"a influência das redes sociais", classe:"Substantivo", categoria:"Psicologia", frase:"L'influence des réseaux sociaux sur les jeunes est étudiée."},
  {fr:"la lecture", pt:"a leitura", classe:"Substantivo", categoria:"Cultura", frase:"La lecture développe l'imagination."},
  {fr:"la littérature", pt:"a literatura", classe:"Substantivo", categoria:"Cultura", frase:"Elle adore la littérature française."},
  {fr:"le cinéma", pt:"o cinema", classe:"Substantivo", categoria:"Cultura", frase:"Ils vont au cinéma tous les vendredis."},
  {fr:"le musée", pt:"o museu", classe:"Substantivo", categoria:"Cultura", frase:"Le musée expose des œuvres contemporaines."},
  {fr:"la gratuité des musées", pt:"a gratuidade dos museus", classe:"Substantivo", categoria:"Cultura", frase:"La gratuité des musées attire plus de visiteurs."},
  {fr:"le patrimoine", pt:"o patrimônio", classe:"Substantivo", categoria:"Cultura", frase:"Ce château fait partie du patrimoine national."},
  {fr:"la culture", pt:"a cultura", classe:"Substantivo", categoria:"Cultura", frase:"La culture reflète l'identité d'un peuple."},
  {fr:"l'accessibilité culturelle", pt:"a acessibilidade cultural", classe:"Substantivo", categoria:"Cultura", frase:"L'accessibilité culturelle profite à tous les publics."},
  {fr:"l'entreprise", pt:"a empresa", classe:"Substantivo", categoria:"Economia", frase:"L'entreprise a embauché dix nouveaux employés."},
  {fr:"le pouvoir d'achat", pt:"o poder de compra", classe:"Substantivo", categoria:"Economia", frase:"Le pouvoir d'achat a diminué cette année."},
  {fr:"l'inflation", pt:"a inflação", classe:"Substantivo", categoria:"Economia", frase:"L'inflation touche surtout les produits alimentaires."},
  {fr:"la spéculation", pt:"a especulação", classe:"Substantivo", categoria:"Economia", frase:"La spéculation fait grimper les prix de l'immobilier."},
  {fr:"la consommation", pt:"o consumo", classe:"Substantivo", categoria:"Economia", frase:"La consommation des ménages a baissé."},
  {fr:"la croissance", pt:"o crescimento", classe:"Substantivo", categoria:"Economia", frase:"La croissance économique reste faible."},
  {fr:"le PIB", pt:"o PIB", classe:"Substantivo", categoria:"Economia", frase:"Le PIB a augmenté de deux pour cent."},
  {fr:"la mondialisation", pt:"a globalização", classe:"Substantivo", categoria:"Economia", frase:"La mondialisation a transformé le commerce international."},
  {fr:"les multinationales", pt:"as multinacionais", classe:"Substantivo", categoria:"Economia", frase:"Les multinationales dominent plusieurs secteurs."},
  {fr:"la compétitivité", pt:"a competitividade", classe:"Substantivo", categoria:"Economia", frase:"La compétitivité des entreprises dépend de l'innovation."},
];

const VOCAB_SEED_VERBOS_ESSENCIAIS = [
  {fr:"parler", pt:"falar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Il parle trois langues."},
  {fr:"aimer", pt:"amar, gostar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Elle aime la musique classique."},
  {fr:"travailler", pt:"trabalhar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Il travaille dans une banque."},
  {fr:"étudier", pt:"estudar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Elle étudie le droit à Paris."},
  {fr:"marcher", pt:"andar, caminhar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Il marche une heure chaque matin."},
  {fr:"regarder", pt:"olhar, assistir", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Ils regardent un film ce soir."},
  {fr:"écouter", pt:"escutar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Elle écoute de la musique en travaillant."},
  {fr:"penser", pt:"pensar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Il pense souvent à son avenir."},
  {fr:"demander", pt:"pedir, perguntar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Elle demande de l'aide à son collègue."},
  {fr:"répondre", pt:"responder", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Il répond rapidement aux e-mails."},
  {fr:"proposer", pt:"propor", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Elle propose une nouvelle idée."},
  {fr:"rencontrer", pt:"encontrar, conhecer", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Ils se sont rencontrés à l'université."},
  {fr:"manquer", pt:"sentir falta, faltar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Sa famille lui manque beaucoup."},
  {fr:"appeler", pt:"chamar, ligar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Elle appelle sa mère tous les jours."},
  {fr:"quitter", pt:"deixar, sair de", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Il a quitté son emploi le mois dernier."},
  {fr:"rentrer", pt:"voltar (para casa)", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Elle rentre tard le vendredi."},
  {fr:"rester", pt:"ficar, permanecer", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Ils restent à la maison ce week-end."},
  {fr:"passer", pt:"passar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Le temps passe vite en vacances."},
  {fr:"habiter", pt:"morar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Il habite près du centre-ville."},
  {fr:"arriver", pt:"chegar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Le train arrive à huit heures."},
  {fr:"voyager", pt:"viajar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Elle voyage souvent pour le travail."},
  {fr:"utiliser", pt:"usar, utilizar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Il utilise son ordinateur tous les jours."},
  {fr:"commander", pt:"pedir (num restaurante), encomendar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Ils commandent une pizza ce soir."},
  {fr:"expliquer", pt:"explicar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Le professeur explique la leçon."},
  {fr:"organiser", pt:"organizar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Elle organise une fête pour son anniversaire."},
  {fr:"préparer", pt:"preparar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Il prépare le dîner pour ses amis."},
  {fr:"remplacer", pt:"substituir", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Ce produit remplace l'ancien modèle."},
  {fr:"démontrer", pt:"demonstrar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Cette étude démontre un lien clair."},
  {fr:"révéler", pt:"revelar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"L'enquête révèle plusieurs irrégularités."},
  {fr:"informer", pt:"informar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Les médias informent le public chaque jour."},
  {fr:"inventer", pt:"inventar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Il a inventé un nouvel outil."},
  {fr:"rentabiliser", pt:"rentabilizar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"L'entreprise cherche à rentabiliser son investissement."},
  {fr:"subventionner", pt:"subvencionar", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"L'État subventionne certains projets écologiques."},
  {fr:"s'intéresser", pt:"interessar-se", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Elle s'intéresse beaucoup à l'histoire."},
  {fr:"attacher", pt:"dar importância a, apegar-se a", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"Il attache beaucoup d'importance à la ponctualité."},
  {fr:"espérer", pt:"esperar (desejar)", classe:"Verbo", categoria:"Verbo Essencial - 1º Grupo (-ER)", frase:"J'espère réussir cet examen."},
  {fr:"choisir", pt:"escolher", classe:"Verbo", categoria:"Verbo Essencial - 2º Grupo (-IR)", frase:"Elle choisit toujours la même option."},
  {fr:"finir", pt:"terminar, acabar", classe:"Verbo", categoria:"Verbo Essencial - 2º Grupo (-IR)", frase:"Il finit son travail à dix-huit heures."},
  {fr:"réussir", pt:"conseguir, ter sucesso", classe:"Verbo", categoria:"Verbo Essencial - 2º Grupo (-IR)", frase:"Elle a réussi son examen."},
  {fr:"réfléchir", pt:"refletir, pensar", classe:"Verbo", categoria:"Verbo Essencial - 2º Grupo (-IR)", frase:"Il réfléchit avant de répondre."},
  {fr:"grandir", pt:"crescer", classe:"Verbo", categoria:"Verbo Essencial - 2º Grupo (-IR)", frase:"Les enfants grandissent vite."},
  {fr:"grossir", pt:"engordar", classe:"Verbo", categoria:"Verbo Essencial - 2º Grupo (-IR)", frase:"Il a grossi pendant les vacances."},
  {fr:"rougir", pt:"corar, ficar vermelho", classe:"Verbo", categoria:"Verbo Essencial - 2º Grupo (-IR)", frase:"Elle rougit facilement."},
  {fr:"investir", pt:"investir", classe:"Verbo", categoria:"Verbo Essencial - 2º Grupo (-IR)", frase:"Ils investissent dans l'immobilier."},
  {fr:"obéir", pt:"obedecer", classe:"Verbo", categoria:"Verbo Essencial - 2º Grupo (-IR)", frase:"L'enfant obéit à ses parents."},
  {fr:"établir", pt:"estabelecer", classe:"Verbo", categoria:"Verbo Essencial - 2º Grupo (-IR)", frase:"Ils ont établi un nouveau contrat."},
  {fr:"être", pt:"ser, estar", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il est content de son travail."},
  {fr:"avoir", pt:"ter", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle a deux enfants."},
  {fr:"aller", pt:"ir", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Ils vont au marché le samedi."},
  {fr:"faire", pt:"fazer", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il fait ses devoirs après l'école."},
  {fr:"pouvoir", pt:"poder", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle peut venir demain."},
  {fr:"vouloir", pt:"querer", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il veut changer de métier."},
  {fr:"devoir", pt:"dever", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle doit finir ce rapport aujourd'hui."},
  {fr:"savoir", pt:"saber", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il sait parler trois langues."},
  {fr:"voir", pt:"ver", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Ils voient leurs amis ce week-end."},
  {fr:"prendre", pt:"pegar, tomar", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle prend le bus tous les matins."},
  {fr:"venir", pt:"vir", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il vient de terminer ses études."},
  {fr:"mettre", pt:"colocar, pôr", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle met la table pour le dîner."},
  {fr:"dire", pt:"dizer", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il dit toujours la vérité."},
  {fr:"écrire", pt:"escrever", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle écrit un roman depuis un an."},
  {fr:"lire", pt:"ler", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il lit un livre par mois."},
  {fr:"croire", pt:"crer, acreditar", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle croit en ses capacités."},
  {fr:"connaître", pt:"conhecer", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il connaît bien cette ville."},
  {fr:"vivre", pt:"viver", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Ils vivent à la campagne."},
  {fr:"suivre", pt:"seguir", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle suit un cours de danse."},
  {fr:"attendre", pt:"esperar (aguardar)", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il attend le bus depuis vingt minutes."},
  {fr:"entendre", pt:"ouvir", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle entend du bruit dans la rue."},
  {fr:"comprendre", pt:"compreender, entender", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il comprend rapidement les consignes."},
  {fr:"apprendre", pt:"aprender", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle apprend l'espagnol depuis un an."},
  {fr:"recevoir", pt:"receber", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il a reçu une bonne nouvelle."},
  {fr:"ouvrir", pt:"abrir", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle ouvre la fenêtre le matin."},
  {fr:"offrir", pt:"oferecer, presentear", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il offre des fleurs à sa mère."},
  {fr:"souffrir", pt:"sofrer", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle souffre du dos depuis des mois."},
  {fr:"sentir", pt:"sentir, cheirar", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il sent une bonne odeur de pain."},
  {fr:"sortir", pt:"sair", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Ils sortent tous les vendredis soirs."},
  {fr:"partir", pt:"partir, ir embora", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle part en vacances demain."},
  {fr:"tenir", pt:"segurar, manter", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il tient à son opinion."},
  {fr:"obtenir", pt:"obter, conseguir", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle a obtenu son diplôme cette année."},
  {fr:"devenir", pt:"tornar-se", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il est devenu directeur du service."},
  {fr:"revenir", pt:"voltar", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle revient de voyage demain."},
  {fr:"envoyer", pt:"enviar", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il envoie un message à son ami."},
  {fr:"prévoir", pt:"prever", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Ils prévoient une hausse des prix."},
  {fr:"permettre", pt:"permitir", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Ce logiciel permet de gagner du temps."},
  {fr:"falloir", pt:"ser preciso, ser necessário", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Il faut partir tôt demain."},
  {fr:"décrire", pt:"descrever", classe:"Verbo", categoria:"Verbo Essencial - 3º Grupo (Irregular)", frase:"Elle décrit précisément la situation."},
];

// Números por extenso 1-200, gerados programaticamente (mesmo padrão da lista
// original: unidades irregulares, "et un"/"et onze" nas dezenas, base vigesimal
// depois de 60 — "soixante-dix"/"quatre-vingts"/"quatre-vingt-dix" — e "cent" +
// dezena/unidade a partir de 100).
const VOCAB_SEED_NUMEROS = (function gerarNumeros() {
  const UNIDADES = ["zéro","un","deux","trois","quatre","cinq","six","sept","huit","neuf","dix",
    "onze","douze","treize","quatorze","quinze","seize"];

  function nomeAte99(n) {
    if (n <= 16) return UNIDADES[n];
    if (n < 20) return "dix-" + UNIDADES[n - 10];
    const DEZ = { 20:"vingt", 30:"trente", 40:"quarante", 50:"cinquante", 60:"soixante" };
    if (n < 70) {
      const base = Math.floor(n / 10) * 10;
      const resto = n % 10;
      if (resto === 0) return DEZ[base];
      if (resto === 1) return DEZ[base] + " et un";
      return DEZ[base] + "-" + UNIDADES[resto];
    }
    if (n < 80) { // 70-79: soixante + (10..19)
      const resto = n - 60;
      if (resto === 11) return "soixante et onze";
      return "soixante-" + nomeAte99(resto);
    }
    if (n < 100) { // 80-99: quatre-vingt(s) + resto
      const resto = n - 80;
      if (resto === 0) return "quatre-vingts";
      return "quatre-vingt-" + nomeAte99(resto);
    }
  }

  function nomeAte200(n) {
    if (n < 100) return nomeAte99(n);
    if (n === 100) return "cent";
    if (n < 200) {
      const resto = n - 100;
      return resto === 0 ? "cent" : "cent " + nomeAte99(resto);
    }
    return "deux cents";
  }

  function numeroPorExtensoPt(n) {
    // só usado pra montar a tradução (pt) — não precisa cobrir regras de acentuação
    // do português com perfeição, é vocabulário de apoio, não gabarito de ditado.
    const U = ["zero","um","dois","três","quatro","cinco","seis","sete","oito","nove","dez",
      "onze","doze","treze","quatorze","quinze","dezesseis","dezessete","dezoito","dezenove"];
    const D = { 20:"vinte", 30:"trinta", 40:"quarenta", 50:"cinquenta", 60:"sessenta", 70:"setenta", 80:"oitenta", 90:"noventa" };
    function ate99(x) {
      if (x < 20) return U[x];
      const base = Math.floor(x / 10) * 10;
      const resto = x % 10;
      return resto === 0 ? D[base] : D[base] + " e " + U[resto];
    }
    if (n < 100) return ate99(n);
    if (n === 100) return "cem";
    if (n < 200) {
      const resto = n - 100;
      return resto === 0 ? "cem" : "cento e " + ate99(resto);
    }
    return "duzentos";
  }

  const lista = [];
  for (let n = 1; n <= 200; n++) {
    if (n === 200) {
      lista.push({fr:"deux cents", pt:"duzentos", classe:"Numeral", categoria:"Números", frase:"Ça coûte deux cents euros."});
      continue;
    }
    lista.push({
      fr: nomeAte200(n),
      pt: numeroPorExtensoPt(n),
      classe: "Numeral",
      categoria: "Números",
      frase: "Ça coûte " + nomeAte200(n) + " euro" + (n > 1 ? "s" : "") + "."
    });
  }
  return lista;
})();

module.exports = { VOCAB_SEED, VOCAB_SEED_VIDA_COTIDIANA, VOCAB_SEED_VERBOS_ESSENCIAIS, VOCAB_SEED_NUMEROS };
